src/main/java/org/flightgear/fgatc/web/PilotBean.java
/*
 *  Copyright (C) 2010 scotth
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.flightgear.fgatc.web;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIInput;
import javax.faces.event.ValueChangeEvent;
import javax.inject.Named;
import org.flightgear.fgatc.ejb.AtcSessionFacade;
import org.flightgear.fgatc.ejb.entity.FlightPlan;
import org.flightgear.fgatc.ejb.entity.User;

/**
 *
 * @author scotth
 */
@ManagedBean(name="pilot")
@SessionScoped
public class PilotBean implements Serializable {
    @EJB
    private AtcSessionFacade facadeEJB;
    private FlightPlan currentPlan;
    @ManagedProperty("#{user}")
    private UserBean usr;

    /** Constants **/

    HashMap aircraftAirspeedDefaults = new HashMap(40);
    HashMap aircraftFLDefaults = new HashMap(40);


    /** Creates a new instance of PilotBean */
    public PilotBean() {
        aircraftAirspeedDefaults.put("A380", "0.85");
        aircraftFLDefaults.put("A380", "380");
        aircraftAirspeedDefaults.put("A320", "0.80");
        aircraftFLDefaults.put("A320", "340");
        aircraftAirspeedDefaults.put("A340", "0.79");
        aircraftFLDefaults.put("A340", "360");
        aircraftAirspeedDefaults.put("A330", "0.80");
        aircraftFLDefaults.put("A330", "360");
        aircraftAirspeedDefaults.put("747", "0.83");
        aircraftFLDefaults.put("747", "380");
        aircraftAirspeedDefaults.put("737", "0.75");
        aircraftFLDefaults.put("737", "340");
        aircraftAirspeedDefaults.put("767", "0.80");
        aircraftFLDefaults.put("767", "360");
    }


    /**
     * @return the currentPlan
     */
    public FlightPlan getCurrentPlan() {
        return currentPlan;
    }

    /**
     * @param currentPlan the currentPlan to set
     */
    public void setCurrentPlan(FlightPlan currentPlan) {
        this.currentPlan = currentPlan;
    }

    /**
     * @return the usr
     */
    public UserBean getUsr() {
        return usr;
    }

    /**
     * @param usr the usr to set
     */
    public void setUsr(UserBean usr) {
        this.usr = usr;
    }


    public String readyNewPlan() {
        this.currentPlan = new FlightPlan();
        this.currentPlan.setDateCreated(new Date());
        this.currentPlan.setOriginatorUsername(usr.getUsername());
        User me = facadeEJB.findUser(usr.username);
        this.currentPlan.setPilotInCommand(me.getGivenName()+" "+me.getFamilyName());
        return "newPlan";
    }

    public String readyNewCompanyPlan() {
        return "newCompanyPlan";
    }

    public String loadAllPlans() {
        return "viewAllPlans";
    }

    public List getAllMyPlans() {
        return facadeEJB.findUserPlans(usr.getUsername());
    }

    public String savePlan() {
        this.currentPlan.setDateCreated(new Date());
        this.currentPlan.setOriginatorUsername(usr.getUsername());
        this.currentPlan.setPlanStatus("PENDING");
        facadeEJB.persist(this.currentPlan);
        return "index";
    }

    public void updatePlanAircraft(ValueChangeEvent e) {
        Logger log = Logger.getLogger(this.getClass().getName()+"updatePlanAircraft");
        UIInput nameInput = (UIInput)e.getComponent();
        String name = (String)nameInput.getValue();
        log.info("Update aircraft for: "+name+", currentType: "+currentPlan.getAircraftType());
        if (this.currentPlan.getCruiseSpeed() == null) {
            Double cruiseSpeed = Double.valueOf((String)aircraftAirspeedDefaults.get(name));
            this.currentPlan.setCruiseSpeed(cruiseSpeed);
            log.info("Updated cruiseSpeed to: "+cruiseSpeed);
        }
        if (this.currentPlan.getFlightLevel() == 0) {
            int flightLevel = Integer.valueOf((String)aircraftFLDefaults.get(name)).intValue();
            this.currentPlan.setFlightLevel(flightLevel);
            log.info("Updated FL to: "+flightLevel);
        }
    }

}

src/main/webapp/pilot/displayPlan.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html">

    <body>

        <ui:composition template="./../templates/pilotTemplate.xhtml">

            <ui:define name="left">
            </ui:define>

            <ui:define name="content">
                <h:form>
                    <h2>Flight Plan</h2>
                    <h:panelGrid columns="2">
                        <h:outputLabel for="" value="Date Created"/>
                        <h:inputText id="" value="#{pilot.currentPlan.dateCreated}"/>
                        <h:outputLabel for="" value="Created by"/>
                        <h:inputText id="" value="#{pilot.currentPlan.originatorUsername}"/>
                        <h:outputLabel for="" value="Aircraft Id"/>
                        <h:inputText id="" value="#{pilot.currentPlan.aircraftId}"/>
                        <h:outputLabel for="" value="Flight Rules"/>
                        <h:inputText id="" value="#{pilot.currentPlan.flightRules}"/>
                        <h:outputLabel for="" value="Flight Type"/>
                        <h:inputText id="" value="#{pilot.currentPlan.flightType}"/>
                        <h:outputLabel for="" value="Aircraft Type"/>
                        <h:inputText id="" value="#{pilot.currentPlan.aircraftType}"/>
                        <h:outputLabel for="" value="Departure"/>
                        <h:inputText id="" value="#{pilot.currentPlan.departureICAO}"/>
                        <h:outputLabel for="" value="Arrival"/>
                        <h:inputText id="" value="#{pilot.currentPlan.destinationICAO}"/>
                        <h:outputLabel for="" value="depart Time"/>
                        <h:inputText id="" value="#{pilot.currentPlan.departureTime}"/>
                        <h:outputLabel for="" value="Cruise Speed"/>
                        <h:inputText id="" value="#{pilot.currentPlan.cruiseSpeed}"/>
                        <h:outputLabel for="" value="Cruise FL"/>
                        <h:inputText id="" value="#{pilot.currentPlan.flightLevel}"/>
                        <h:outputLabel for="" value="Route"/>
                        <h:inputText id="" value="#{pilot.currentPlan.route1}"/>
                        <h:outputLabel for="" value="Route (cont)"/>
                        <h:inputText id="" value="#{pilot.currentPlan.route2}"/>
                        <h:outputLabel for="" value="Route (cont)"/>
                        <h:inputText id="" value="#{pilot.currentPlan.route3}"/>
                        <h:outputLabel for="" value="Route (cont)"/>
                        <h:inputText id="" value="#{pilot.currentPlan.route4}"/>
                        <h:outputLabel for="" value="Total Est Endurance Time"/>
                        <h:inputText id="" value="#{pilot.currentPlan.totalEET}"/>
                        <h:outputLabel for="" value="Alternate ICAO"/>
                        <h:inputText id="" value="#{pilot.currentPlan.alternateICAO}"/>
                        <h:outputLabel for="" value="Fuel on-board"/>
                        <h:inputText id="" value="#{pilot.currentPlan.fuelOnboardTime}"/>
                        <h:outputLabel for="" value="Persons on-board"/>
                        <h:inputText id="" value="#{pilot.currentPlan.personsOnboard}"/>
                        <h:outputLabel for="" value="Aircraft Markings/colour"/>
                        <h:inputText id="" value="#{pilot.currentPlan.aircraftColourMarkings}"/>
                        <h:outputLabel for="" value="Pilot In Command name"/>
                        <h:inputText id="" value="#{pilot.currentPlan.pilotInCommand}"/>
                        <h:outputLabel for="" value="Plan status"/>
                        <h:inputText id="" value="#{pilot.currentPlan.planStatus}"/>
                    </h:panelGrid>
                    <h:commandButton action="#{pilot.savePlan}" value="Save"/>
                </h:form>
            </ui:define>

        </ui:composition>

    </body>
</html>

src/main/webapp/pilot/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html">
    
    <body>
        
        <ui:composition template="./../templates/pilotTemplate.xhtml">
            
            <ui:define name="left">
            </ui:define>

            <ui:define name="content">
                <p>Here you can lodge your flight plan with the departure airport, and managed regular scheduled flight plans for your company.</p>
                <h:form>
                    
                </h:form>
            </ui:define>

        </ui:composition>
        
    </body>
</html>

src/main/webapp/pilot/newCompanyPlan.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html">
    
    <body>
        
        <ui:composition template="./../templates/pilotTemplate.xhtml">
            
            <ui:define name="left">
            </ui:define>

            <ui:define name="content">
                <h:form>
                    <h2>New Company Plan</h2>
                </h:form>
            </ui:define>

        </ui:composition>
        
    </body>
</html>

src/main/webapp/pilot/newPlan.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <body>

        <ui:composition template="./../templates/pilotTemplate.xhtml">

            <ui:define name="left">
            </ui:define>

            <ui:define name="content">
                <h:form>
                    <h2>New Plan</h2>
                    <h:panelGrid id="inputGrid" columns="2">
                        <h:outputLabel for="aircraftId" value="Aircraft Id/Callsign"/>
                        <h:inputText id="aircraftId" value="#{pilot.currentPlan.aircraftId}"/>
                        <h:outputLabel for="flightRules" value="Flight Rules"/>
                        <h:selectOneMenu id="flightRules" value="#{pilot.currentPlan.flightRules}">
                            <f:selectItem itemValue="VFR"/>
                            <f:selectItem itemValue="IFR"/>
                        </h:selectOneMenu>
                        <h:outputLabel for="flightType" value="Flight Type"/>
                        <h:selectOneMenu id="flightType" value="#{pilot.currentPlan.flightType}">
                            <f:selectItem itemLabel="Scheduled" itemValue="S"/>
                            <f:selectItem itemLabel="Non-Scheduled" itemValue="N"/>
                            <f:selectItem itemLabel="General Aviation" itemValue="GA"/>
                            <f:selectItem itemLabel="Military/Police/Customs" itemValue="M"/>
                            <f:selectItem itemLabel="Other" itemValue="X"/>
                        </h:selectOneMenu>
                        <h:outputLabel for="aircraftType" value="Aircraft Type"/>
                        <h:inputText id="aircraftType" value="#{pilot.currentPlan.aircraftType}" valueChangeListener="#{pilot.updatePlanAircraft}">
                            <f:ajax immediate="true" render="cruiseSpeed flightLevel" execute="@this" event="blur"/>
                        </h:inputText>
                        <h:outputLabel for="departureICAO" value="Departure"/>
                        <p:autoComplete  maxResults="40" queryDelay="500"  completeMethod="#{atc.autoQueryICAOSimple}" id="departureICAO" value="#{pilot.currentPlan.departureICAO}"/>
                        <h:outputText value="&nbsp;"/>
                        <h:outputText value="&nbsp;"/>
                        <h:outputLabel for="destinationICAO" value="Arrival"/>
                        <p:autoComplete maxResults="40"  queryDelay="600" completeMethod="#{atc.autoQueryICAOSimple}" id="destinationICAO" value="#{pilot.currentPlan.destinationICAO}"/>
                        <!-- p:autoComplete maxResults="40"  queryDelay="600" var="aero2" completeMethod="#{atc.autoQueryICAO}" itemLabel="#{aero2.icaoId} (#{aero2.fullName})" itemValue="#{aero2.icaoId}" id="destinationICAO" value="#{pilot.currentPlan.destinationICAO}"/ -->
                        <h:outputText value="&nbsp;"/>
                        <h:outputText value="&nbsp;"/>
                        <h:outputLabel for="departureTime" value="Depart Time UTC (hh:mm)"/>
                        <p:inputMask mask="99:99" size="5" id="departureTime" value="#{pilot.currentPlan.departureTime}">
                            <f:convertDateTime type="time" pattern="HH:mm"/>
                        </p:inputMask>
                        <h:outputLabel for="cruiseSpeed" value="Cruise Speed"/>
                        <h:inputText id="cruiseSpeed" size="3" value="#{pilot.currentPlan.cruiseSpeed}"/>
                        <h:outputLabel for="flightLevel" value="Cruise FL"/>
                        <h:inputText id="flightLevel" size="3" value="#{pilot.currentPlan.flightLevel}"/>
                        <h:outputLabel for="route1" value="Route"/>
                        <h:inputTextarea cols="51" rows="5" id="route1" value="#{pilot.currentPlan.route1}"/>
                        <h:outputLabel for="totalEET" value="Total Est Elapse Time"/>
                        <p:inputMask mask="99:99" size="4" id="totalEET" value="#{pilot.currentPlan.totalEET}">
                            <f:convertDateTime type="time" pattern="HH:mm"/>
                        </p:inputMask>
                        <h:outputLabel for="alternateICAO" value="Alternate ICAO"/>
                        <p:autoComplete maxResults="40" queryDelay="600" var="aero2" completeMethod="#{atc.autoQueryICAO}" itemLabel="#{aero2.icaoId} (#{aero2.fullName})" itemValue="#{aero2.icaoId}" id="alternateICAO" value="#{pilot.currentPlan.alternateICAO}"/>
                        <h:outputLabel for="fob" value="Fuel on-board"/>
                        <p:inputMask mask="99:99" size="4" id="fob" value="#{pilot.currentPlan.fuelOnboardTime}">
                            <f:convertDateTime type="time" pattern="HH:mm"/>
                        </p:inputMask>
                        <h:outputLabel for="pob" value="Persons on-board"/>
                        <h:inputText id="pob" value="#{pilot.currentPlan.personsOnboard}"/>
                        <h:outputLabel for="markings" value="Aircraft Markings/colour"/>
                        <h:inputText id="markings" value="#{pilot.currentPlan.aircraftColourMarkings}"/>
                        <h:outputLabel for="pic" value="Pilot In Command name"/>
                        <h:inputText id="pic" value="#{pilot.currentPlan.pilotInCommand}"/>
                    </h:panelGrid>
                    <h:commandButton action="#{pilot.savePlan}" value="Save"/>
                </h:form>
            </ui:define>

        </ui:composition>

    </body>
</html>

src/main/webapp/pilot/viewAllPlans.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    
    <body>
        
        <ui:composition template="./../templates/pilotTemplate.xhtml">
            
            <ui:define name="left">
            </ui:define>

            <ui:define name="content">
                <h:form>
                    <h2>All Plans</h2>
                    <h:dataTable var="plan" value="#{pilot.allMyPlans}" cellpadding="3">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Depart time (UTC)"/>
                            </f:facet>
                            <h:outputText value="#{plan.departureTime}">
                                <f:convertDateTime type="time" pattern="HH:mm"/>
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Id/Callsign"/>
                            </f:facet>
                            <h:outputText value="#{plan.aircraftId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Depart"/>
                            </f:facet>
                            <h:outputText value="#{plan.departureICAO}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Arrival"/>
                            </f:facet>
                            <h:outputText value="#{plan.destinationICAO}"/>
                        </h:column>
                    </h:dataTable>
                </h:form>
            </ui:define>

        </ui:composition>
        
    </body>
</html>